### ISSUE TITLE
vue-now-ui-dashboard-pro-laravel Login Issue

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-vue-now-ui-dashboard-pro-laravel#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes ] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Expected behaviour should be working properly with login credentials

# Current Behavior

Currently Not able to get login in the dashboard

# Failure Information (for bugs)

It simply shows invalid credentials even though I have tested the credentials in the DB too.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
### Laravel API Project Installation
Navigate in your Laravel API project folder: cd your-laravel-json-api-project
Install project dependencies: composer install
Create a new .env file: cp .env.example .env
Add your own database credentials in the .env file in DB_DATABASE, DB_USERNAME, DB_PASSWORD
Create users table: php artisan migrate --seed
Generate application key: php artisan key:generate
Install Laravel Passport: php artisan passport:install

Vue Now UI Dashboard Project Installation
Navigate to your Vue Now UI Dashboard project folder: cd your-vue-now-ui-dashbord-project
Install project dependencies: npm install
Create a new .env file: cp .env.example .env
VUE_APP_BASE_URL should contain the URL of your Vue Now Ui Dashboard Project (eg. http://localhost:8080/)
VUE_APP_API_BASE_URL should contain the URL of your Laravel JSON:API Project. (eg. http://localhost:3000/api/v1)
Run npm run dev to start the application in a local development environment or npm run build to build release distributable.

admin type - [admin@jsonapi.com] with the password secret

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Window 64 bit
* 
* Operating System: Device name	DEEP-001
Processor	Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz   3.10 GHz
Installed RAM	4.00 GB
System type	64-bit operating system, x64-based processor

* Browser and Version: Version 105.0.5195.127 (Official Build) Chrome

## Failure Logs

Please include any relevant log snippets or files here.
![Vue-Now-UI-Dashboard-PRO-Laravel-by-Creative-Tim-UPDIVISION](https://user-images.githubusercontent.com/114389867/192233408-d4a826cb-d3b9-4663-86e4-b10604da9f12.png)

**Comment by teamupdivision** [comment]
Hello,

Thanks for reporting this issue and for using Creative Tim products.

Could you please send the .env for both the frontend and backend, please? 

Thank you. 

All the best, 
Adrian.

**Comment by ghost** [comment]
Hi Adrian,

Yeah sure, PFA

*Regards:*
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

My apologies, i cannot seem to find the attached files could you please try sending them again? 

Thank you. 

All the best,
Adrian

**Comment by ghost** [comment]
Hi Adrian,

PFA

*Regards:*
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

I still cannot see them could you please send the files from the github issues link? 

https://github.com/creativetimofficial/ct-vue-now-ui-dashboard-pro-laravel/issues/1

Thank you.

**Comment by ghost** [comment]
Hi Adrian,

I am not able to attach the file here as well so I am pasting the code here of both the files.

### Laravel env file code:

APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:H3mz38XaVPiXAbzu6EvBvlGq+2+unZNcR+FVJnGHY5k=
APP_DEBUG=true
APP_URL=

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravelvue_db
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"



### Vue env file code:

VUE_APP_BASE_URL=http://localhost:8080/
VUE_APP_API_BASE_URL=http://localhost/vue-now-ui-dashboard-pro-laravel/laravel-json-api-pro/public/api/v1
VUE_APP_API_KEY=
VUE_APP_IS_DEMO=

**Comment by ghost** [comment]
Hi Adrian,

Please check on GitHub and let me know where i am going wrong.


*Regards:*
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

It looks like you do not have client_id and Client_secret set up in env can you please add them?

Also, can you install passport an let us know if it works?

If that does not work can you please let us know if the issue is present in postman as well or just frontend? 

Thank you.

**Comment by ghost** [comment]
Hi Adrian,

Thanks For your quick response.

Yes I have run the passport install command and after that, I had the client_id and Client_secret, but I have not any idea where and how to add them in the env file. can you please just let me know how can I add those credentials to the laravel env file?

PFA

Thanks
Regards
![localhost-127-0-0-1-laravelvue_db-oauth_clients-phpMyAdmin-5-2-0](https://user-images.githubusercontent.com/114389867/192483632-1ccc74f1-1f0e-41a2-9408-bb7f45d4e9ed.png)

Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello, 

Go ahead and change the env file code with this :

APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:H3mz38XaVPiXAbzu6EvBvlGq+2+unZNcR+FVJnGHY5k=
APP_DEBUG=true
APP_URL=
LOG_CHANNEL=stack
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravelvue_db
DB_USERNAME=root
DB_PASSWORD=
BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1
MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

CLIENT_ID=2
CLIENT_SECRET=rGC...( Copy Values from secret column row id 1)

Please let me know if that worked.

**Comment by ghost** [comment]
Hi Adrian,

![image](https://user-images.githubusercontent.com/114389867/192493727-c7d3ab5b-e5ad-4aa9-8002-e60e9db5681c.png)


Here is the error which i am getting before and now as well

Here is my code snippet of env file

![image](https://user-images.githubusercontent.com/114389867/192493926-7cd04f9c-78ba-499a-a71e-10a340ced5c4.png)


Regards:
Pardeep Rawat

**Comment by ghost** [comment]
Hi Adrian,

Is there anything you need from my side? I am available now to provide any information.

Thanks

Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello, 

Could you please clarify if it works in postman? 

Thank you.

**Comment by ghost** [comment]
Hi Adriane,

I didn't know how to run this on postman.

Could you please make steps on how can I do that? what credentials and what link I have to try on postman.
https://drive.google.com/file/d/1J8dGvDvTJ6OnCQBqZ6UzNexuOaAkMoHe/view?usp=sharing

Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

Please find the link with the full collection of endpoints from postman -> https://www.postman.com/updivision/workspace/updivision-s-public-workspace/collection/8138626-e8410c91-d19e-48d2-915d-e458c1db78b2

You can also find some help with the setup here --> https://learning.postman.com/docs/sending-requests/managing-environments/

You just need to set up the local environment cu the api_url and access_token variables.

**Comment by ghost** [comment]
Hi Adriane,

I didn't know now what to do. I am able to run the login API and it's giving me the below o/p

https://drive.google.com/file/d/1dgNiDOIURVup3XzQnInED8JYVMkBon7K/view?usp=sharing

Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

Could you please check the console and send us what issues you find or a screenshot?

**Comment by ghost** [comment]
Hi Adriane,

PFA
https://drive.google.com/file/d/1v2G38RyQHrskLayfgKT2VXuMFqD0usC4/view?usp=sharing
https://drive.google.com/file/d/1h23qm2w744C3oRQ1WIQolTzTQbVjbQ7p/view?usp=sharing

Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

My apologies i wasn't clear enough. I mean the Frontend console, you get there by right clicking in the page selecting "inspect" and selecting console in the menu that appears. Please send us what appears after you click submit.
Also could you send us the Paypload from the network?

**Comment by ghost** [comment]
Hi Adriane,

PFA,

![image](https://user-images.githubusercontent.com/114389867/192527525-4c776148-2f70-4d4d-9ba6-c8935748a9ec.png)

Also, thanks for your support will connect tomorrow again as it's my working hour over today. I hope you will understand.


Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

Understood. For tomorrow you should turn on api backend projects.

**Comment by ghost** [comment]
Hi Adriane,

I hope you are doing well.

Thanks for your understanding should we start? and what I have to do today?

Regards:
Pardeep Rawat

**Comment by eugentudorache** [comment]
Hi Pardeep,

Please read the above reply.
Your backend API project is not turned on, please turn it on.

Best

--
Eugen Tudorache Technical Director & Co-Founder m: +40 733 926 398 e: ***@***.*** ***@***.*** w: www.updivision.com [http://www.updivision.com/]
On 28/09/2022 6:57:27, Pardeeprawat001 ***@***.***> wrote:
Hi Adriane,
I hope you are doing well.
Thanks for your understanding should we start? and what I have to do today?
Regards:
Pardeep Rawat

**Comment by ghost** [comment]
Hi Eugene,

I didn't get your point. How can I turn the backend API Project? Please guide me on how to do that.

Regards:
Pardeep Rawat

**Comment by ghost** [comment]
Hi Eugene,

I Have tried and tested the **register** API and it's working for me. But when I tried to log in with those credentials it's giving me the same error. here is the attached screenshot for registering API. 
![image](https://user-images.githubusercontent.com/114389867/192687011-445ed19b-0218-46ef-8e05-87f81af9845d.png)


Regards:
Pardeep Rawat

**Comment by ghost** [comment]
Hi Adriane,

Any feedback?

Regards:
Pardeep Rawat

**Comment by ghost** [comment]
Hi Adrian,

I didn't get your point. How can I turn the backend API Project? Please
guide me on how to do that.

Any feedback?

*Regards:*
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

You will turn the backend API the same way you did the postman. 

Does register work from the Frontend?

**Comment by ghost** [comment]
Hi,

No, not from the front end. Can you please guide me how can I do with backend API as I haven't any idea about it.

Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

The backend API should already be on since it worked for postman. 

Could you please send us another screenshot from the console with all the errors that appear? 

Thank you.

**Comment by teamupdivision** [comment]
Hello,

Also did you make any changes to the project?

**Comment by ghost** [comment]
No, I haven't changed anything expect the env files.

PFA
![image](https://user-images.githubusercontent.com/114389867/192764578-525ce9b6-6330-4734-8b5a-16c0a534cb7b.png)

Regards:
Pardeep Rawat

**Comment by ghost** [comment]
Hello

Attached screenshot of chrome as well
![image](https://user-images.githubusercontent.com/114389867/192764924-d373813e-689a-4f0c-ac4e-7041544f7b5f.png)


Regards:
Pardeep Rawat

**Comment by ghost** [comment]
Hi Adrian,

I hope you are doing well!

Any feedback regarding the above? I am eagerly waiting for your response.


Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
We're still investigating the issue, we will follow up soonest.

**Comment by ghost** [comment]
Okay Thanks,

I hope I will soon get good feedback from you.


Regards:
Pardeep Rawat
*Regards:*
Pardeep Rawat

**Comment by teamupdivision** [comment]
Please go to package.json and update  `"vue-authenticate": "^1.4.1"` to `"vue-authenticate": "1.4.1"`
After that, run `npm update`

**Comment by ghost** [comment]
Hi 

I have updated and still getting same issue . here is the attached screenshot of my console.

![image](https://user-images.githubusercontent.com/114389867/193008565-715396da-d456-43a4-8f75-6b8850d3ce78.png)
Regards:
Pardeep

**Comment by teamupdivision** [comment]
Please try deleting **node_modules** and **package.lock** then do **npm install**

**Comment by ghost** [comment]
Hi,

deleting node_modules and package.lock then do npm install:: **Done also run the dev command after that.**

Found the Below Error when run the npm dev command, and still getting the same error when try to run login.

![image](https://user-images.githubusercontent.com/114389867/193029064-ac152a8e-b24e-46b5-bf41-a9367af4ceec.png)
![image](https://user-images.githubusercontent.com/114389867/193029202-cec608d6-b581-4ec8-950c-36f72fa27bfe.png)
![image](https://user-images.githubusercontent.com/114389867/193029245-9eef3300-6199-447f-b92b-c70a217b69eb.png)


Regards:
Pardeep Rawat

**Comment by ghost** [comment]
Hi Adrine,

Good Morning, I hope you doing well.

Is there any way I can provide you with my vue laravel pro project and you run it on your local machine and send me all the necessary steps I need to follow after that? I think this can help me to get rid of this.

Regards:
Pardeep Rawat

**Comment by eugentudorache** [comment]
Hello,

I don't understand - why would you send us the project?
Did you make any changes to it? If not there is no reason to send it.

Thank you

--
Eugen Tudorache Technical Director & Co-Founder m: +40 733 926 398 e: ***@***.*** ***@***.*** w: www.updivision.com [http://www.updivision.com/]
On 30/09/2022 7:41:24, Pardeeprawat001 ***@***.***> wrote:
Hi Adrine,
Good Morning, I hope you doing well.
Is there any way I can provide you with my vue laravel pro project and you run it on your local machine and send me all the necessary steps I need to follow after that? I think this can help me to get rid of this.
Regards:
Pardeep Rawat

**Comment by ghost** [comment]
Hi Eugene,

I get it but my main reason is to run this project asap, as I am running out of time.

Thanks & Regards
Pardeepb Rawat

**Comment by teamupdivision** [comment]
We cannot help you unless you reinstall it and send us the process screen cast.

**Comment by ghost** [comment]
Hi Adriene,

I had done all the necessary processes and now it's working to me now could
you help me build on the production server?

I am mentioning all the structure of my project because I am confused
between paths.

Main Server: https://secure.voxara.net/

Sub Folder:  https://secure.voxara.net/laravelvue/  * #In the laravel
folder I have placed two projects one for laravel and the other for vue.*

Laravel Project:
https://secure.voxara.net/laravelvue/laravel-json-api-pro/public/

https://secure.voxara.net/laravelvue/laravel-json-api-pro/public/index.php/api/v1

Vue Project:  https://secure.voxara.net/laravelvue/vue/index.html

Another Issue: When I do a hard refresh on the register, login, and
dashboard it gives me a 404 not found URL. Is there any way I can set the
global path for all the URLs?
eg: https://secure.voxara.net/laravelvue/vue/register


Note: I have made some changes regarding app.js file the which is present
in vue project. I am telling you just for your reffernce.
      path: /laravelvue/vue/js/app.6ebee391.js

*Regards:*
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

 If you need help with any of your projects, we're happy to help. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Comment by ghost** [comment]
Hi Adriene,

I hope you doing well.

I have one question for you can you please look at this issue and why I am getting this issue?

Items API:  http://localhost/final-laravel-vue/laravel/public/api/v1/items

When I am trying to access the above endpoint it gives me an error. Error attached in the screenshot
https://drive.google.com/file/d/1a2rH04vBNM0XiY2S-ILHLo0AWZfwT05i/view?usp=sharing

Also after that, I tried to run the endpoint in postman, and here it is also giving me an unauthenticated error.
https://drive.google.com/file/d/1zyOL47-o72seX8ayYHQ9tU9no3rCxLCV/view?usp=sharing

Also, one thing  I am not aware of that and that is the Bearer Token. I don't know how to set this. please tell me the steps of setting the bearer token.

Thanks
Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello, 

In the Postman collection witch you can find here --> https://www.postman.com/updivision/workspace/updivision-s-public-workspace   everything is set up including the Bearer Token.

You are getting Unauthenticated means you are trying to access a route unlogged. 

Thank you.

**Comment by ghost** [comment]
Hi Adriene,

I hope You are doing well.

May I know why I am getting this error?
![image](https://user-images.githubusercontent.com/114389867/194542194-b2d8dea7-0710-461c-be31-abcd2ac95d78.png)

I cannot see the Item List, even my Examples Tab in the left panel is not loaded completely?
![image](https://user-images.githubusercontent.com/114389867/194542486-e6bcabce-aeab-4f9e-b86b-30000d339704.png)


Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

It looks like you are getting error 401, which means that you are logged in as a user not authorized to view items.

**Comment by ghost** [comment]
Hi Adriene,

Okay, got it but I am trying to log in with the below credentials, and I think these credentials have access to Item Tab but still, I am getting the same error.
Username admin@jsonapi.com , Password secret


Let me tell you one thing about the local environment all three types of login are working perfectly but when I make connect laravel API with the live server then it is giving me an error.
![image](https://user-images.githubusercontent.com/114389867/194562174-e48c55a7-1cfd-4fdc-aa82-8fe864b8c649.png)

Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

Could you please send some screenshots with the errors when you use the admin credentials?

**Comment by ghost** [comment]
Hello Sir,

Here is the short video I made. I hope this is what you want.
https://www.awesomescreenshot.com/video/11588263?key=72e668c600c2068f8010088e0ed7d584

Regards:
Pardeep Rawat

**Comment by ghost** [comment]
Hi Adrine,

Good Morning,

I didn't get your response?

Regards:
Pardeep Rawat

**Comment by eugentudorache** [comment]
Hello,We need more details in order to debug yorr problem. Please completely remove both projects and reinstall them. Pleasw also record the screen and send us the recording.Thank youEugenOn 29 Sep 2022, at 15:21, Pardeeprawat001 ***@***.***> wrote:﻿
Hi,
deleting node_modules and package.lock then do npm install:: Done also run the dev command after that.
Found the Below Error when run the npm dev command, and still getting the same error when try to run login.



Regards:
Pardeep Rawat

**Comment by eugentudorache** [comment]
I'm sorry, but we'll not debug your local project, it will not help you in any way.
Please reinstall it.

Thank you

--
Eugen Tudorache Technical Director & Co-Founder m: +40 733 926 398 e: ***@***.*** ***@***.*** w: www.updivision.com [http://www.updivision.com/]
On 30/09/2022 7:55:52, Pardeeprawat001 ***@***.***> wrote:
Hi Eugene,
I get it but my main reason is to run this project asap, as I am running out of time.
Thanks & Regards
Pardeepb Rawat

**Comment by teamupdivision** [comment]
Hello, did you make changes to the default users and roles?

**Comment by ghost** [comment]
Hi Eugine,

No, I didn't make any changes in the default user and roles.

*Regards:*
Pardeep Rawat

**Comment by ghost** [comment]
Hi Adriene,

I hope you are doing well.

Yesterday I made a repository and uploaded my Vue project there. I have uploaded the whole dist folder there you can check it. Is it helpful for you to diagnose the issue?

Link: https://pardeeprawat001.github.io/finalaravel/

Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello Pardeep,

Could you please send us a database dump? 

Thank you.

**Comment by ghost** [comment]
Hi Adrine,

PFA
[laravelvuedb.zip](https://github.com/creativetimofficial/ct-vue-now-ui-dashboard-pro-laravel/files/9761803/laravelvuedb.zip)

Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,

Could you please try incognito?

If that does not work, go ahead and delete everything you have in storage.

From what we can see after the login the next requests are perceived as not being logged in.

Unfortunately we cannot reproduce any of your issues.

**Comment by ghost** [comment]
Hi Adriene,

Sorry for the late reply. i hope you doing well.

Here we have done as per your request. Please watch the videos and tell me what I am doing wrong here.

**In the Below Videos, laravel is working from a live server and my vue is on local Environment.**
Laravel API Project Installation(Server)
Part 1: https://www.loom.com/share/fa09d69de2b84f769ac85a3f0544346c 
Part 2: https://www.loom.com/share/c9821a7604294420b0e4768d3a303bb4 

Vue Now UI Dashboard Project Installation
https://www.loom.com/share/f0b02b03d3e140eca692a8bb3502d309

Note: As you can see, we are having a problem with the EXAMPLES (API) Tab. Only two menu are showing 1) User Profile 2) Item Management. as in local environment all the menus under the Examples (API) tab are working fine.

/*****************************************************************************************************************************/

**In the Below Videos laravel as well as vue are in the local environment.**
Laravel API Project Installation(Local) and set up with vue project
https://www.loom.com/share/5b512fc1d4f1404a81900b1011dc914c

Note: As I mentioned earlier on local setup its working fine here local setup means vue, as well as laravel both, are on local environment. 

If you have any questions let me please let me know.

Regards:
Pardeep Rawat

**Comment by teamupdivision** [comment]
Hello,
I'm sorry but this is no longer a ticket about support with the product. If it's working on your local env, it means it needs to work everywhere. You clearly have an issue on the deploy. Please try as we said before to delete your local storage.
Thank you
