### ISSUE TITLE
Live Search on Selectpicker not getting focus

### ISSUE THREAD

**Issue by nathron** [creativetimofficial/ct-vue-now-ui-dashboard-pro-laravel#2]
Greetings,
I'm experiencing the same issue with both Dashboards of yours I'm using (both Laravel).

When the select dropdown is opened and the live search option enabled, I expect to get the search box focused automatically, but it doesn't happen. I get it to be focused hitting Tab key only (or clicking on it, of course).

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM products. 

Could you please send us a screen shot of your screen so we may see what the issue is ? 

Thank you.

**Comment by nathron** [comment]
<img width="1085" alt="bug 1" src="https://user-images.githubusercontent.com/10529991/202413543-a33f0399-5a46-4fbc-a3d3-769826d82d65.png">
And this is the code I use to generate that specific select (but it goes like that for all the others too)
`<select  data-live-search="true" data-style="form-control" style="width:100%"   name="client_id" id="client_id" data-size="7" class="flex-fill selectpicker{{ $errors->has('client_id') ? ' is-invalid' : '' }}" required >`

**Comment by nathron** [comment]
I've seen the code didn't show for some reason... I copy that here without the >

select  data-live-search="true" data-style="form-control" style="width:100%"   name="client_id" id="client_id" data-size="7" class="flex-fill selectpicker{{ $errors->has('client_id') ? ' is-invalid' : '' }}" required

**Comment by rarestoma** [comment]
Hi @nathron,

Thank you for working with our products.

Can you please give us your repo link or access to it so we can test it?

Regards,
Rares

**Comment by nathron** [comment]
Hi,
I've just made a bogus page on my dev site with basically just one select, and the behaviour is there, here's the link
https://dev.mduevr.com/select
it's not under auth so you can see it freely, thanks in advance

**Comment by nathron** [comment]
Good Morning,
any news on this? Thanks a lot in advance.

**Comment by nathron** [comment]
Is there any news for this? My deadline is approaching fast and I need to find a solution.
Thanks in advance

**Comment by rarestoma** [comment]
Hi @nathron,

Can you please give me the link to your repo so I can download and test it?

Regards,
Rares

**Comment by dragosct** [comment]
Hi, @nathron! Please try the below code and the #mySelect should be replaced with your selectpicker ID.

```js
$('#mySelect').on('show.bs.select', function () {
  $('#mySelect').find(".bs-searchbox input").focus();
}); 
```

Regards,
Dragos

**Comment by nathron** [comment]
@rarestoma added you to a repo where I'm having the issue
@dragosct I've found that already but it doesn't work, and I *think* it couldn't work either, as #mySelect is the select itself, while the searchbox is in the divs added by bootstrap to its parent. I've tried doing a very hacky `$('#mySelect').parent().parent().find(".bs-searchbox input").focus();` to no avail, while `$('#mySelect').parent().parent().find(".bs-searchbox input").val('foo');` will work as intended

**Comment by nathron** [comment]
@rarestoma Tried substituing the last version of bootstrap-select [https://developer.snapappointments.com/bootstrap-select/](url) instead of the bootstrap-selectpicker.js 
the focus worked (css was botched though)

**Comment by rarestoma** [comment]
Hi @nathron,

Great to hear that it is working now.

Please let us know anytime you need help.

Regards,
Rares

**Comment by nathron** [comment]
No, it is not working!
Using another version of the selectpicker it gets the focus, but everything
else is botched!
You are using a modified and or integrated version of it, using the other
one is messing on many other aspects and so the selects are unusable.
It's only a hint you can use to find the issue

Il mer 23 nov 2022, 14:04 Toma Rares ***@***.***> ha scritto:

**Comment by nathron** [comment]
@rarestoma 
Just making sure you haven't flagged this to solved...

**Comment by nathron** [comment]
@rarestoma is there any update on this issue?
Thanks

**Comment by nathron** [comment]
@rarestoma @dragosct @alexandru-paduraru 
Is there a way to get an answer about this? Thanks

**Comment by dragosct** [comment]
@nathron Sorry for the late response! It was a very busy period for us. We will come back with an update. Thanks for patience

**Comment by rarestoma** [comment]
Hi @nathron, just saw now your message on Discord. We will continue there solving this issue as we can communicate much faster.

**Comment by nathron** [comment]
@dragosct @rarestoma 
Ok. Now I know you still have this on your todo list. I'll wait for the update and will keep to monitor here.
I'm available for any question if needed.
Thanks

**Comment by rarestoma** [comment]
@nathron Can you please tell me what is the route where this problem exists so I can check?

**Comment by nathron** [comment]
@rarestoma on /schedule for example, but generally on any place where a selectpicker is inserted. Thanks

**Comment by rarestoma** [comment]
@nathron I tried accessing the route but it requires login, I tried creating an account but I get the following error: Unknown column 'role_id' in 'field list'.

Can you please give me all the steps that I need to make so I can access the /schedule route?
