### ISSUE TITLE
Frontend & Backend connection error

### ISSUE THREAD

**Issue by adrluizspark** [creativetimofficial/ct-vue-now-ui-dashboard-pro-laravel#3]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Failure Information (for bugs)

Same issue fixed here: https://github.com/creativetimofficial/vue-now-ui-dashboard-laravel/issues/1

When everything is setup n both apps are running, frontend is showing an empty page & cmd shows an error message of
"export 'VueAuthenticate' was not found in 'vue-authenticate'"

When this line if fixed to be
import { VueAuthenticate } from "vue-authenticate"; => import VueAuthenticate from "vue-authenticate";
The application works and the login page show up, but can't login or register

@ login it says "Invalid credentials!" although the default user is seeded into database
@ register it says "something went wrong"

Ps: I think it's not api credentials problem because when I tried to "forgot password" api works fine.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Download Code
2. Fix VueAuthenticate bug 
3. Try login or register

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: MacBook Pro 13-inch M2 2022
* Operating System: Ventura 13.2.1
* Browser and Version: Chrome - Firefox - Safari

**Comment by teamupdivision** [comment]
Hello,

Thank you for using creative TIM products. 

Could you please let us know what version of node you are using?

You need VUE 16 for the project to run properly. 

Let us know if that helps. 

Thank you.

**Comment by adrluizspark** [comment]
Could you please let us know what version of node you are using?
* Node 14 
* when I try to run npm install with node 16 it returns the following error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vue-now-ui-dashboard-pro@1.1.0
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.9.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from eslint-plugin-vue@6.2.2
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"^6.2.2" from the root project

**Comment by teamupdivision** [comment]
Hello, 

Can you try cloning your project again then and let us know if it works? 

Thank you.

**Comment by adrluizspark** [comment]
Clone? I download from creative tim website, Pro version I don't found any repository to clone, and the package.json  still "name": "vue-now-ui-dashboard-pro",
"version": "1.1.0",
Free version is working only the pro version I have problem.

**Comment by teamupdivision** [comment]
Hello, 

We cannot recreate the same issue.

What i meant is, can you redownload the project without making any changes to it? And let us know if that fixes the issue.

Thank you.

**Comment by adrluizspark** [comment]
Same problem, after I fix the authenticate problem I got Invalid Credentials (login page) and Opps something went wrong (register page)

log:
vue.runtime.esm.js?2b0e:4605 [Vue warn]: Error in v-on handler (Promise/async): "TypeError: Cannot read properties of undefined (reading 'data')"

found in

---> <Login> at src/pages/Dashboard/Pages/Login.vue
       <ZoomCenterTransition>
         <AuthLayout> at src/pages/Dashboard/Pages/AuthLayout.vue
           <App> at src/App.vue
             <Root>
warn @ vue.runtime.esm.js?2b0e:4605
logError @ vue.runtime.esm.js?2b0e:3045
globalHandleError @ vue.runtime.esm.js?2b0e:3041
handleError @ vue.runtime.esm.js?2b0e:3008
eval @ vue.runtime.esm.js?2b0e:3019
Promise.catch (async)
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:3019
invoker @ vue.runtime.esm.js?2b0e:1815
original_1._wrapper @ vue.runtime.esm.js?2b0e:7473

**Comment by adrluizspark** [comment]
<img width="1095" alt="Screenshot 2023-03-03 at 09 55 32" src="https://user-images.githubusercontent.com/126615186/222725585-532d7d2d-3fef-440f-bbb7-86257ed105e0.png">
<img width="1439" alt="Screenshot 2023-03-03 at 09 56 12" src="https://user-images.githubusercontent.com/126615186/222725745-c04a4064-b288-4f81-9bf3-4a9d61f21e98.png">
<img width="1436" alt="Screenshot 2023-03-03 at 09 56 52" src="https://user-images.githubusercontent.com/126615186/222725815-f7900f56-945e-46d9-8cfd-ad7bd67dad92.png">

**Comment by adrluizspark** [comment]
I tried this one and it didn't work either.

<img width="1077" alt="Screenshot 2023-03-03 at 10 05 45" src="https://user-images.githubusercontent.com/126615186/222727568-306dfc46-1bab-4f46-9e35-6a8f4e8894ca.png">

**Comment by teamupdivision** [comment]
Hello,

Could you please make sure that you have "vue-authenticate": "1.4.1" in package.json.

Thank you.
